#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus UI Version 24.1.0-p089
#--------------------------------------------------------------------------------------

quantus  -log_file /home/hrahimi/projects/POTENTIOSTAT_26/ASSURA_LVS/6_TIA_Front_Layout/qrc.6_TIA_Front_Layout.log -cmd /home/hrahimi/projects/POTENTIOSTAT_26/ASSURA_LVS/6_TIA_Front_Layout/qrc.6_TIA_Front_Layout.ccl 
